### ISSUE TITLE
add github action for checking availability of demos

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#104]
в swaponline/mcw есть e2e тесты которые запускают пупитер https://github.com/swaponline/MultiCurrencyWallet/blob/master/tests/e2e/utils.ts. нужно сделать экшн на основе этого https://github.com/Anshuman71/tweet-my-articles/blob/main/.github/workflows/update-twitter-banner.yml#L8 

который будет просто запускать пару раз в день проверку, что загружаются апки

https://test.crosschain.onout.xyz/
https://test.dex.onout.xyz/

заодно он будет держать кеш пинаты в актуальном состоянии, потому что если не дергать файлы то сайты дико долго грузятся. 

но сначала проверить будут ли грузится домены вообще в экшине

**Comment by VitaliyShulik** [comment]
Где сделать эти actions? в этом репозитории?

**Comment by noxonsu** [comment]
да тут норм

**Comment by VitaliyShulik** [comment]
https://github.com/noxonsu/dash.onout.org/actions/workflows/check-ipfs-domains.yml
