### ISSUE TITLE
replace all the urls in cron tests

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#121]
поменять урлы с ipfs на обычные которые используются в демках. ipfs хостинг это фейл. добавить в мониторинг остальные продукты

**Comment by VitaliyShulik** [comment]
Окей, как буду добавлять сети во все продукты клиенту одному - добавлю айдишники для подключения кошелька для теста этого в другие продукты...

**Comment by VitaliyShulik** [comment]
@noxonsu а что там с логами?

**Comment by noxonsu** [comment]
https://dashapi.onout.org/ не работает, так же нужно добавить в мониторинг

**Comment by VitaliyShulik** [comment]
> https://dashapi.onout.org/ не работает, так же нужно добавить в мониторинг

нужно собрать отдельный пул API для проверки и сделать отдельный мониторинг тест для этого...
