### ISSUE TITLE
add BUY USING VISA/MC

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#128]
при нажатии на кнопку показать окно со следующими ссылками . это нужно чтоб если у чела не хватает денег предлагать ему докупить по карте. 

https://changelly.com/buy/bnb 
https://www.binance.com/en/buy-BNB

следовательно если у чела выбран мейннет то показывать ссылки для покупки ETH , а для полигона - матик https://buy.itez.com/

**Comment by NotEternal** [comment]
#124
