### ISSUE TITLE
add token cashback

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#30]
1. выпустить токен (erc20)
2. сделать чтоб при оплате продукта человек получал по 50 токенов за каждую покупку
3. т.е. он оплачивает товар и получает тут же на свой адрес 50 токенов

**Comment by NotEternal** [comment]
Example / template  https://github.com/NotEternal/contracts/blob/main/contracts/Dash.sol

**Comment by Nasirdin** [comment]
needs review
