### ISSUE TITLE
Add Google analytics events

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#49]
нужно настроить воронку, добавить на кнопку покупки событие для гугл аналитики (я добавил тебя как админа вроде), захода в продукт, нажатие на документацию. нужно понять где отваливаются пользователи

https://zozimus.com/how-to-track-a-button-click-event-in-google-analytics-using-google-tag-manager/

**Comment by NotEternal** [comment]
https://www.npmjs.com/package/react-ga

https://github.com/Uniswap/interface/blob/main/src/components/analytics/index.ts
