### ISSUE TITLE
check mobile version and add prices to catalog

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#54]
![photo_2022-03-16_20-31-00](https://user-images.githubusercontent.com/2914674/158651598-70e123ff-5780-4ca8-8c33-a711b71288e9.jpg)

- [x] картинка поехала и занимает огромное пространство
- [x] так же нужно добавить прайс акутальный прямо в каталог, а то сейчас надо заходить внутрь

**Comment by VitaliyShulik** [comment]
На iPhone 5S что-ли экран?)
