### ISSUE TITLE
add api cache 

### ISSUE THREAD

**Issue by noxonsu** [noxonsu/dash.onout.org#61]
https://dashapi.onout.org/check?address=0x3B85D38c3A7AEabABA8B7DEb7a73177688270abC отвечает долго иногда. думаю если true то можно в браузере кэшировать ответ и не дергать каждый ращ

**Comment by NotEternal** [comment]
the same #41

**Comment by VitaliyShulik** [comment]
В общем сделал, чтобы на один день без проверок после проверки
