### ISSUE TITLE
Referal info validation

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/dash.onout.org#92]
![image](https://user-images.githubusercontent.com/61930014/162674359-ca50f089-adbc-419f-906b-9a2fc5b64785.png)

нужно проверять `contract`, будет ошибка если подключиться через эфир

- [проблема тут](https://github.com/noxonsu/dash.onout.org/blob/532d559f0752dea3f5d114a31e14590fc95adf56/src/components/Affiliate/index.tsx#L22)

**Comment by noxonsu** [comment]
- [ ] сюдаже. не работает счетчик приглашенных клиентов. (показывает по нулям)
